Travis extensions
ipa320/cob_object_perception pull request #54
Opened 2017-07-31 08:36 UTC by ipa-rmb

2017-07-31 12:24 UTC, fmessmer requested changes

2017-07-31 12:24 UTC, ipa-fxm commented on .travis.yml
> +    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=debianmatrix:
there is a typo (additional `:`)

2017-07-31 12:37 UTC, ipa-rmb commented
Yes, a line break got lost.

2017-08-01 09:29 UTC, ipa-rmb commented
Kinetic fails because of another problem. Will be fixed in an upcoming PR.

2017-08-01 09:32 UTC, ipa-jcl approved these changes

2017-08-01 09:36 UTC, fmessmer approved these changes

2017-08-01 09:37 UTC, merged